### ISSUE TITLE
PCB validation 

### ISSUE THREAD

**Issue by HelenTanGitHub** [HelenTanGitHub/SmolDesignProject#1]
Hi Dr. Palmeri,

I'm very sorry for the late uploads. Could you please check my PCB design?

**Comment by sphaerobolus** [comment]
Looks pretty good to me. You don't actually need the voltage regulator because the Nano has a regulator on board. If you want to save one component, you could route the 9V from your battery directly to the Vin pin. The on-board regulator will do its magic. You'll have 5V available at the 5V pin.
